Repository PKNU-VCD/pknu-vcd-fe, pull requests merged in 2025-08, with the labels that each got.

#18 [refactor] 방명록 댓글 UI 수정
  src/components/guestbook/guestbookInput/GuestbookInput.styles.ts
  src/components/guestbook/guestbookInput/GuestbookInput.tsx
Labels: 홍주 🧀, UI/UX 🎨

#20 [refactor] 버튼 스타일파일 분리
  src/components/Button/Button.tsx
  src/components/button/Button.styles.ts
Labels: 성원🏰, refactor🔨

#24 [feature] 한영 변환 패널 구현
  src/assets/.gitkeep
  src/assets/icons/down.svg
  src/assets/icons/up.svg
  src/components/.gitkeep
  src/components/translationPanel/TranslationPanel.styles.ts
  src/components/translationPanel/TranslationPanel.tsx
  src/stories/TranslationPanel.stories.tsx
  src/styles/theme.ts
  src/types/.gitkeep
Labels: 홍주 🧀, UI/UX 🎨

#27 [feature] 푸터 구현
  src/assets/icons/ColorInstaIcon.svg
  src/assets/icons/ColorYoutubeIcon.svg
  src/assets/icons/FootLogo.svg
  src/assets/icons/InstaIcon.svg
  src/assets/icons/YoutubeIcon.svg
  src/components/footer/Footer.stories.tsx
  src/components/footer/Footer.styles.ts
  src/components/footer/Footer.tsx
  src/styles/theme.ts
Labels: 성원🏰, UI/UX 🎨

#29 [feature] 공통 인풋필드 UI 제작
  src/assets/icons/DeleteIcon.svg
  src/components/inputField/InputField.stories.tsx
  src/components/inputField/InputField.styles.ts
  src/components/inputField/InputField.tsx
Labels: 성원🏰, UI/UX 🎨

#31 [feature] 버튼 반응형 스타일 추가
  src/components/Button/Button.tsx
  src/components/button/Button.styles.ts
  src/styles/theme.ts
Labels: 성원🏰, UI/UX 🎨

#33 [feature] 헤더 UI 제작
  src/assets/icons/HeaderIcon.svg
  src/assets/icons/Union.svg
  src/components/Button/Button.tsx
  src/components/button/Button.styles.ts
  src/components/header/Header.stories.tsx
  src/components/header/Header.styles.ts
  src/components/header/Header.tsx
  src/styles/global.ts
Labels: 성원🏰, UI/UX 🎨

#35 [feature] 파일 추가 및 업로드 버튼 UI 제작
  src/assets/icons/FileUploadIcon.svg
  src/components/Button/Button.tsx
  src/components/button/Button.styles.ts
  src/stories/button/Button.stories.tsx
  src/stories/footer/Footer.stories.tsx
  src/stories/header/Header.stories.tsx
  src/stories/inputField/InputField.stories.tsx
Labels: 성원🏰, UI/UX 🎨

#43 [chore] 네트리파이 플러그인 추가
  netlify.toml
Labels: 성원🏰

#42 featrue: 메인페이지 구현
  package-lock.json
  package.json
  src/app/main/canvas/Dot.ts
  src/app/main/canvas/canvas.tsx
  src/app/main/page.styles.ts
  src/app/main/page.tsx
  src/app/page.styles.tsx
  src/app/page.tsx
  src/assets/icons/BlinkHeaderIcon.svg
  src/assets/icons/Floating_1.svg
  src/assets/icons/Floating_2.svg
  src/assets/icons/Floating_3.svg
  src/assets/icons/HeaderIcon.svg
  src/components/blinkingLogo/BlinkingLogo.style.ts
  src/components/blinkingLogo/BlinkingLogo.tsx
  src/components/floatingDraggable/FloatingDraggable.tsx
  src/components/footer/Footer.styles.ts
  src/components/header/Header.tsx
  src/components/thumbnailGrid/thumbnail/Thumbnail.styles.ts
  src/stories/page.stories.tsx
  src/styles/theme.ts
  src/types/assets.d.ts
Labels: UI/UX 🎨, feature ⚒️
